config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: { registrations: "users/registrations", passwords: "users/passwords" }
  get "alert_email_password/index"
  get "new_user_notice/index"
  get "home", to: "home#index", as: "home"
  resources :positions
  resources :departments
  resources :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :position
  validates :full_name, :birthday, :gender, :cpf, :phone, :rg, :email, :contract_date, :salary, :status, :adress, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["contract_date"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["position"]
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @q = Employee.joins(position: :department).ransack(params[:q])
    @employees = @q.result(distinct: true).includes(position: :department)
    @departments = Department.all 
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy!

    respond_to do |format|
      format.html { redirect_to employees_path, status: :see_other, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:full_name, :birthday, :gender, :cpf, :rg, :phone, :email, :position_id, :contract_date, :salary, :status, adress: [:street, :number, :complement, :neighborhood, :city, :state, :cep])
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div class="pt-4" id="<%= dom_id employee %>">
  <h2 class="text-2xl font-geinst text-center">Informações do funcionário</h2>
  <p class="my-5">
    <span class="block font-medium mb-1">Nome completo:</span>
    <%= employee.full_name %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Data de nascimento:</span>
    <%= employee.birthday %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Gênero:</span>
    <%= employee.gender %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">CPF:</span>
    <%= employee.cpf %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">RG:</span>
    <%= employee.rg %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Telefone:</span>
    <%= employee.phone %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Email:</span>
    <%= employee.email %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Cargo:</span>
    <%= employee.position_id %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Data de contratação:</span>
    <%= employee.contract_date %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Salário:</span>
    <%= employee.salary %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Status:</span>
    <%= employee.status %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true, class: "contents") do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3 text-center">
      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :full_name, "Nome Completo:" %> <br>
    <%= form.text_field :full_name, autocomplete: :off, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :birthday, "Data de Nascimento:" %> <br>
    <%= form.date_field :birthday, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :gender, "Gênero:" %> <br>
  
    <%= form.radio_button :gender, "Masculino" %>
    <%= form.label :gender_male, "Masculino" %> <br>
    <%= form.radio_button :gender, "Feminino" %>
    <%= form.label :gender_female, "Feminino" %> <br>
    <%= form.radio_button :gender, "Outro" %>
    <%= form.label :gender_other, "Outro" %>
  </div>
  <div class="my-5">
    <%= form.label :cpf, "CPF:" %> <br>
    <%= form.number_field :cpf, autocomplete: :off, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :rg, "RG:" %> <br>
    <%= form.number_field :rg, autocomplete: :off, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div>
    <p class="font-semibold text-lg">Endereço</p>
    <div class="my-5">
      <%= form.label :adress_street, "Rua:" %> <br>
      <%= form.text_field :adress, autocomplete: :off, value: employee.adress["street"], name: "employee[adress][street]",class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= form.label :adress_number, "Número:" %> <br>
      <%= form.number_field :adress, autocomplete: :off, value: employee.adress["number"], name: "employee[adress][number]", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
        <%= form.label :adress_complement, "Complemento:" %> <br>
        <%= form.text_field :adress, autocomplete: :off, value: employee.adress["complement"], name: "employee[adress][complement]", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= form.label :adress_neighborhood, "Bairro:" %> <br>
      <%= form.text_field :adress, autocomplete: :off, value: employee.adress["neighborhood"], name: "employee[adress][neighborhood]", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div>
      <%= form.label :adress_city, "Cidade" %> <br>
      <%= form.text_field :adress, autocomplete: :off, value: employee.adress["city"], name: "employee[adress][neighborhood]", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= form.label :adress_state, "Estado:" %> <br>
      <%= form.text_field :adress, autocomplete: :off, value: employee.adress["state"], name: "employee[adress][state]", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  
    <div class="my-5">
      <%= form.label :adress_number, "CEP:" %> <br>
      <%= form.text_field :adress, autocomplete: :off, value: employee.adress["cep"], name: "employee[adress][cep]", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  </div>
  <div class="my-5">
    <%= form.label :phone, "Telefone:" %> <br>
    <%= form.telephone_field :phone, autocomplete: :off, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :email, "Email:" %> <br>
    <%= form.email_field :email, autocomplete: :off, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :position, "Cargo:" %> <br>
    <%= form.collection_select :position_id, Position.all, :id, :name, { prompt: "Selecione um cargo:" }, { class: "w-full border-gray-400 rounded-md shadow " } %>
  </div>
  <div class="my-5">
    <%= form.label :contract_date, "Data de contratação:" %> <br>
    <%= form.date_field :contract_date, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :salary, "Salário:" %> <br>
    <%= form.number_field :salary, autocomplete: :off, min: 0, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :status, "Status:" %> <br>
  
    <%= form.radio_button :status, "Ativo" %>
    <%= form.label :status_active, "Ativo" %>
    <%= form.radio_button :status, "Inativo" %>
    <%= form.label :status_inactive, "Inativo" %>
    <%= form.radio_button :status, "Em Licença" %>
    <%= form.label :status_on_leave, "Em Licença" %>
  </div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-2 px-4 bg-blue text-white inline-block font-medium cursor-pointer" %>
  </div>

<% end %>

app/views/employees/edit.html.erb
<div class="mx-auto md:w-2/3 w-full mb-4">
  <div class="max-w-xl mx-auto">
    <h1 class="font-bold text-4xl text-center mt-4">Editando funcionário</h1>

    <%= render "form", employee: @employee %>

    <%= link_to "Mostrar funcionário", @employee, class: "rounded-lg py-2 px-4 bg-blue text-white inline-block font-medium cursor-pointer" %>
    <%= link_to "Voltar", employees_path, class: "rounded-lg py-2 px-4 bg-blue text-white inline-block font-medium cursor-pointer" %>
  </div>
</div>

app/views/employees/index.html.erb
<div class="max-w-5xl mx-auto px-4">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl font-geinst">Funcionários</h1>
    <div class="flex space-x-4">
        <%= link_to "Criar novo funcionário", new_employee_path, class: "rounded-lg py-3 px-5 bg-blue text-white block font-medium my-4 shadow-md" %>
    </div>
  </div>

  <div data-controller="filter" class="my-3">
      <%= link_to "Filtros", nil, remote: true, class: "rounded-lg py-3 px-5 bg-blue text-white inline font-medium shadow-md",
        data: {
          action: "click->filter#toggle"
        }
      %>
    <div data-filter-target="show" class="hidden">
      <%= render "filters/filters_employees", employee: @employee, department: @department%>
    </div>
  </div>

  <div id="employees" class="min-w-full mt-10">
    <% @employees.each do |employee| %>
      <div class="flex justify-between">
        <div>
          <p class="text-lg">Nome: <%= employee.full_name %> </p>
          <p class="text-lg">Cargo: <%= employee.position.name %> </p>
          <p class="text-lg">Departamento: <%= employee.position.department.name %> </p>
          <p class="text-lg">Data de contratação: <%= l(employee.contract_date) %></p>
        </div>
        <p class="text-lg"> <%= link_to "Detalhes", employee, class: "rounded-lg py-1 px-4 bg-blue text-white inline-block font-medium cursor-pointer mt-2 shadow-md" %> </p>
      </div>
      <hr class="my-4 border-gray-400">
    <% end %>
  </div>
</div>

app/views/employees/new.html.erb
<div class="mx-auto md:w-2/3 max-w-2xl py-6">
  <h1 class="font-bold text-2xl font-geinst text-center">Adicionar novo funcionário</h1> 

  <%= render "form", employee: @employee %>
</div>

app/views/employees/show.html.erb
<div class="mx-auto md:w-2/3 max-w-2xl my-5">
  <%= render @employee %>

  <%= link_to "Editar informações", edit_employee_path(@employee), class: "rounded-lg py-2 px-4 bg-blue text-white inline-block font-medium cursor-pointer" %>
  <%= link_to "Voltar", employees_path, class: "rounded-lg py-2 px-4 bg-blue text-white inline-block font-medium cursor-pointer" %>
  <div class="inline-block">
    <%= button_to "Deletar funcionário", @employee, method: :delete, class: "rounded-lg py-2 px-4 bg-blue text-white inline-block font-medium cursor-pointer" %>
  </div>
</div>