config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: { registrations: "users/registrations", passwords: "users/passwords" }
  get "alert_email_password/index"
  get "new_user_notice/index"
  get "home", to: "home#index", as: "home"
  resources :positions
  resources :departments
  resources :employees
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :department
  has_many :employees
  validates :name, :description, :department, :level, :base_salary, :requirements, :benefits, :status, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["department_id"]
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: %i[ show edit update destroy ]

  # GET /positions or /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1 or /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions or /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: "Position was successfully created." }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1 or /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: "Position was successfully updated." }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1 or /positions/1.json
  def destroy
    @position.destroy!

    respond_to do |format|
      format.html { redirect_to positions_path, status: :see_other, notice: "Position was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def position_params
      params.require(:position).permit(:name, :description, :department_id, :level, :base_salary, :requirements, :benefits, :status)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_with(model: position, class: "contents") do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
        <% position.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5"> 
    <%= form.label :name, "Nome" %> <br>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5"> 
    <%= form.label :description, "Descrição" %> <br> 
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5"> 
    <%= form.label :department_id, "Departamento" %> <br>
    <%= form.collection_select :department_id, Department.all, :id, :name, prompt: "Selecione um departamento: ",class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5"> 
    <%= form.label :level, "Nível de acesso"%> <br>
    <%= form.select :level, ["Júnior", "Pleno", "Sênior", "Não se aplica"] , class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5"> 
    <%= form.label :base_salary, "Salário base" %> <br>
    <%= form.text_field :base_salary, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5"> 
    <%= form.label :requirements, "Requisitos" %> <br>
    <%= form.text_area :requirements, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5"> 
    <%= form.label :benefits, "Benefícios" %> <br>
    <%= form.text_area :benefits, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5"> 
    <%= form.label :status, "Status" %> <br>
    <%= form.select :status, ["Ativo", "Inativo"] ,class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/positions/_position.html.erb
<div id="<%= dom_id position %>">
  <p class="my-5">
    <span class="block font-medium mb-1">Nome:</span>
    <%= position.name %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Descrição do cargo:</span>
    <%= position.description %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Departamento:</span>
    <%= position.department.name %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Nível do funcionário:</span>
    <%= position.level %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Base salarial:</span>
    R$ <%= position.base_salary %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Requirementos:</span>
    <%= position.requirements %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Benefícios:</span>
    <%= position.benefits %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Status:</span>
    <%= position.status %>
  </p>

</div>

app/views/positions/edit.html.erb
<div class="mx-auto md:w-2/3 max-w-2xl my-4">
  <h1 class="text-4xl font-geinst text-center">Editando cargo</h1>

  <%= render "form", position: @position %>

  <%= link_to "Mostrar", @position, class: "ml-2 rounded-lg py-3 px-5 bg-blue text-white inline-block font-medium" %>
  <%= link_to "Voltar", positions_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue text-white inline-block font-medium" %>
</div>

app/views/positions/index.html.erb
<div class="max-w-5xl mx-auto mt-4">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl font-geinst">Cargos</h1>
      <%= link_to "Criar novo cargo", new_position_path, class: "rounded-lg py-3 px-5 bg-blue text-white block font-medium" %>
    </div>
    <div id="positions" class="min-w-full mt-10">
      <% @positions.each do |position| %>
        <div class="flex justify-between">
          <%= tag.span position.name, class: "text-lg" %>
          <%= link_to "Mostrar cargo", position, class: "rounded-lg py-3 px-5 bg-blue text-white block font-medium" %>
        </div>
        <hr class="my-4 border-gray-400">
      <% end %>
    </div>
</div>

app/views/positions/new.html.erb
<div class="mx-auto md:w-2/3 max-w-2xl my-4">
  <h1 class="font-bold text-2xl font-geinst text-center">Adicionar novo cargo</h1>

  <%= render "form", position: @position %>

  <%= link_to "Voltar", positions_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue text-white inline-block font-medium" %>
</div>

app/views/positions/show.html.erb
<div class="mx-auto md:w-2/3 max-w-2xl my-5">
  <h1 class="text-center font-geinst text-2xl">Informações do cargo</h1>

  <%= render @position %>
  
  <%= link_to "Editar cargo", edit_position_path(@position), class: "mt-2 rounded-lg py-3 px-5  bg-blue text-white inline-block font-medium shadow-md" %>
  <%= link_to "Voltar", positions_path, class: "ml-2 rounded-lg py-3 px-5  bg-blue text-white inline-block font-medium shadow-md" %>
  <div class="inline-block ml-2">
    <%= button_to "Deletar cargo", @position, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-blue text-white font-medium shadow-md" %>
  </div>
</div>