config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: { registrations: "users/registrations", passwords: "users/passwords" }
  get "alert_email_password/index"
  get "new_user_notice/index"
  get "home", to: "home#index", as: "home"
  resources :positions
  resources :departments
  resources :employees
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :positions
  has_and_belongs_to_many :users
  after_create :assign_to_admins
  validates :name, :description, :code, :adress, :status, presence: true

  private 

  def assign_to_admins 
    User.where(acess: "admin").each do |admin|
      admin.departments << self unless admin.departments.include?(self)
    end
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[ show edit update destroy ]
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  # GET /departments or /departments.json
  def index
    @departments = policy_scope(Department)
  end

  # GET /departments/1 or /departments/1.json
  def show
    authorize @department
  end

  # GET /departments/new
  def new
    @department = Department.new
    authorize @department
  end

  # GET /departments/1/edit
  def edit
    authorize @department
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)
    authorize @department

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    authorize @department
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    authorize @department
    @department.destroy!

    respond_to do |format|
      format.html { redirect_to departments_path, status: :see_other, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:name, :description, :code, :status, adress: [:street, :number, :complement, :neighborhood, :city, :state, :cep])
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.html.erb
<div class="mx-auto" id="<%= dom_id department %>">
  <p class="my-5">
    <span class="text-lg block font-medium mb-1">Nome:</span>
    <%= department.name %>
  </p>

  <p class="my-5">
    <span class="text-lg block font-medium mb-1">Descrição:</span>
    <%= department.description %>
  </p>

  <p class="my-5">
    <span class="text-lg block font-medium mb-1">Código do departamento:</span>
    <%= department.code %>
  </p>

  <div class="my-5">
    <span class="text-lg block font-medium mb-1">Endereço:</span>
    <p>Rua: <%= department.adress["street"] %></p>
    <p>Número: <%= department.adress["number"]%></p>
    <p>Complemento: <%= department.adress["complement"]%></p>
    <p>Bairro: <%= department.adress["neighborhood"]%></p>
    <p>Cidade: <%= department.adress["city"] %></p>
    <p>Estado: <%= department.adress["state"] %></p>
    <p>CEP: <%= department.adress["cep"] %></p>
  </div>

  <p class="my-5">
    <span class="text-lg block font-medium mb-1">Status:</span>
    <%= department.status %>
  </p>

</div>

app/views/departments/_form.html.erb
<%= form_with(model: department, class: "contents") do |form| %>
  <% if department.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, "Departamento:" %> <br>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description, "Descrição:" %> <br>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :code, "Código do Departamento:" %> <br>
    <%= form.text_field :code, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div>
    <p>Endereço</p>
    <div class="my-5">
      <%= form.label :adress_street, "Rua:" %> <br>
      <%= form.text_field :adress, value: department.adress["street"], name: "deparment[adress][street]",class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :adress_number, "Número:" %> <br>
      <%= form.text_field :adress, value: department.adress["number"], name: "department[adress][number]", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
       <%= form.label :adress_complement, "Complemento:" %> <br>
       <%= form.text_field :adress, value: department.adress["complement"], name: "department[adress][complement]", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :adress_neighborhood, "Bairro:" %> <br>
      <%= form.text_field :adress, value: department.adress["neighborhood"], name: "department[adress][neighborhood]", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div>
      <%= form.label :adress_city, "Cidade" %> <br>
      <%= form.text_field :adress, value: department.adress["city"], name: "department[adress][neighborhood]", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :adress_state, "Estado:" %> <br>
      <%= form.text_field :adress, value: department.adress["state"], name: "department[adress][state]", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    
    <div class="my-5">
      <%= form.label :adress_number, "CEP:" %> <br>
      <%= form.text_field :adress, value: department.adress["cep"], name: "department[adress][cep]", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  </div>

  <div class="my-5">
    <%= form.label :status, "Status:" %> <br>
    <%= form.select :status, ["Ativo", "Inativo"],class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline"> <br>
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<div class="mx-auto md:w-2/3 my-5">
  <h1 class="font-bold text-4xl">Editando departamento</h1>

  <%= render "form", department: @department %>

  <%= link_to "Mostrar", @department, class: "ml-2 rounded-lg py-3 px-5 bg-blue text-white inline-block font-medium" %>
  <%= link_to "Voltar", departments_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue text-white inline-block font-medium" %>
</div>

app/views/departments/index.html.erb
<div class="mx-auto max-w-5xl my-4">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl font-geinst">Departamentos</h1>
    <%= link_to "Criar novo departamento", new_department_path, class: "rounded-lg py-3 px-5 bg-blue text-white block font-medium shadow-md" %>
  </div>

  <div id="departments" class="min-w-full mt-5">
    <% @departments.each do |department| %>
      <div class="flex justify-between items-center">
        <%= tag.span department.name, class: "text-lg" %>
        <%= link_to "Mostrar departamento", department, class: "ml-2 rounded-lg py-3 px-5 bg-blue text-white inline-block font-medium shadow-md" %>
      </div>
      <hr class="my-5 border-gray-400">
    <% end %>
  </div>
</div>

app/views/departments/new.html.erb
<div class="mx-auto md:w-2/3 max-w-2xl my-5">
  <h1 class="font-bold font-geinst text-center text-2xl">Adicionar novo departamento</h1>

  <%= render "form", department: @department %>

  <%= link_to "Voltar", departments_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue text-white inline-block font-medium" %>
</div>

app/views/departments/show.html.erb
<div class="mx-auto md:w-2/3 max-w-2xl my-5">
  <h1 class="font-geinst text-center text-2xl">Informações do departamento</h1>

  <%= render @department %>

  <%= link_to "Editar departamento", edit_department_path(@department), class: "mt-2 rounded-lg py-3 px-5 bg-blue text-white inline-block font-medium" %>
  <%= link_to "Voltar", departments_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue text-white inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Deletar departamento", @department, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-blue text-white font-medium" %>
  </div>
</div>